<a href="https://colab.research.google.com/github/enjelianna/DataMining_MODUL2_Pengenalan-dan-Instalasi-Data-Mining-Tool/blob/main/Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from sklearn.datasets import load_iris
import numpy as np
from sklearn import tree

iris = load_iris()
test_index = [0,50,100]

print(iris.feature_names)
print(iris.target_names)
print(iris.data[0])
print(iris.target[0])
for i in range(10):
  print("sample %d: label %s, features %s" %(i, iris.target[i], iris.data[i]))



['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[5.1 3.5 1.4 0.2]
0
sample 0: label 0, features [5.1 3.5 1.4 0.2]
sample 1: label 0, features [4.9 3.  1.4 0.2]
sample 2: label 0, features [4.7 3.2 1.3 0.2]
sample 3: label 0, features [4.6 3.1 1.5 0.2]
sample 4: label 0, features [5.  3.6 1.4 0.2]
sample 5: label 0, features [5.4 3.9 1.7 0.4]
sample 6: label 0, features [4.6 3.4 1.4 0.3]
sample 7: label 0, features [5.  3.4 1.5 0.2]
sample 8: label 0, features [4.4 2.9 1.4 0.2]
sample 9: label 0, features [4.9 3.1 1.5 0.1]


In [9]:
#training data
train_target = np.delete(iris.target, test_index)
train_data = np.delete(iris.data, test_index, axis=0)
#testing data
test_target = iris.target[test_index]
test_data = iris.data[test_index]

classifier = tree.DecisionTreeClassifier()
classifier.fit(train_data, train_target)

#cetak label asli
print(test_target)
#cetak hasil prediksi
print(classifier.predict(test_data))



[0 1 2]
[0 1 2]
